apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'slack-notifications'
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      routes:
      - match:
          alertname: BackendPodRestarts
        receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/REPLACE_ME'
        channel: '#alerts'
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']
