apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-pod-restart-rule
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: backend.rules
    rules:
    - alert: BackendPodRestarts
      expr: increase(kube_pod_container_status_restarts_total{pod=~"backend.*"}[10m]) > 3
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Backend pod restarted more than 3 times in 10 minutes"
        description: "The backend pod has restarted more than 3 times in the last 10 minutes."
