apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/IYXYI/kube-todo-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: todos
        - name: POSTGRES_USER
          value: todo_user
        - name: POSTGRES_PASSWORD
          value: todo_pass
        livenessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
