apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  labels:
    app: postgres
  namespace: default
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
        id SERIAL PRIMARY KEY,
        text TEXT NOT NULL,
        done BOOLEAN NOT NULL DEFAULT FALSE
    );
